### ISSUE TITLE
time.Duration type is not marshalled to/from queries

### ISSUE THREAD

**Issue by wrouesnel** [cznic/ql#112]
The time.Duration type is currently marshalled into and out of queries as an int64 type which is consistent with the underlying go type but produces a panic when doing the obvious thing and passing actual time.Duration types in and out.

It feels like the underlying code is missing a type switch somewhere to pick up the difference. It'd be good to fix since ql looks super appealing in supporting 'native' go types.

**Comment by cznic** [comment]
I'm not sure where exactly the problem is rooted. The "native" API is designed to handle `time.Duration` values without problems. The `database/sql` API, OTOH depends on a limited types model, represented and documented at [`database/sql/driver.Value`](https://golang.org/pkg/database/sql/driver/#Value). Plase note that `time.Duration` is not one of the type supported by `database/sql/driver`, so "degrading" `time.Duration` to `int64` is the only option available, AFICT. Please let me know if I'm mistaken, thank you. Maybe a small reproduction case would enlighten me ;-)

**Comment by wrouesnel** [comment]
I think that actually explains it - I didn't know about the db/sql library being limited, which of course is what I'm using.

**Comment by wrouesnel** [comment]
In fact that's exactly it. Closing this.
