### ISSUE TITLE
ORDER BY only return rows if there is an implicit index

### ISSUE THREAD

**Issue by eliasnaur** [cznic/ql#124]
I've created a test that demonstrates 2 issues:

https://play.golang.org/p/oxwbAIBIQT

Running go test gives

--- FAIL: TestIndex (0.10s)
	index_test.go:41: unknown field _date
	index_test.go:44: TestIndex: got  exp 1234

- First, the the error at line 41 is triggered because ql requires any fields listed in ORDER BY to also be listed in SELECT. That's unexpected for fields only used for sorting, and requires dummy arguments to Scan.
- Secondly, the error at line 44 indicates that a row was returned but the `str` field contained nothing. That is wrong, since there is no row with an empty `str` field.

It seems that adding an explicit CREATE INDEX on the date fields makes ORDER BY work as expected (line 55-71). Requiring an index for ORDER BY is fine by me, except that then the documentation contains confusing language:

> Now certain SELECT statements may use the indices to speed up joins and/or to speed up record set filtering when the WHERE clause is used; or the indices might be used to improve the performance when the ORDER BY clause is present.

And even if an explicit index is required, I would expect an error from Query when using ORDER BY with no supporting index, at the very least sql.ErrNoRows, and not rows with empty value.

FWIW; I used -tags purego when I installed ql.

**Comment by cznic** [comment]
(A) Error at line 41 is real wrt the documentation. I have yet to figure out what to fix. The problem is that the [select statement evaluation order](https://godoc.org/github.com/cznic/ql#hdr-Select_statement_evaluation_order) reflects how the engine works, ie. at step 5 all non selected expressions do not propagate to later stages. Fixing this is probably possible, but not exactly trivial, I'm afraid. I'll check other SQL dialects for guidelines.

(B) Error at line 44 cannot be considered. When an non nil error is returned at line 40 the program cannot expect any valid results. `t.Error` at line 41 should be `t.Fatal`.

(C) The last issue, `ORDER BY` magically starts to work as documented when an index exists, is caused by the query planner and it sort of works as expected as the outcome is that the `SELECT` expessions are not used at all when an appropriate index exists.

I have long ago planned to add automatic indexes, ie. to compute the index on the fly when needed, as indicated by the planner, but non-existent. Adding this feature will automagically solve (A). Non trivial, but beneficial except for small tables where the overhead can actually slow down the query. (Comparable how a linear search can outperform smarter data structures for small N.)

Opinions/thoughts/ideas?

**Comment by eliasnaur** [comment]
You're right about line 44 of course, and I seem to have confused myself with what seemed like a bug that ORDER BY didn't work at all without explicit indices, even when including all fields in SELECT. As I can't reproduce that error, the only remaining complaint is (A), that the ORDER BY fields have to be SELECT'ed.

With that in mind, I think this issue should be closed. If you think it is worth fixing (A) another issue should be filed for that only.
