### ISSUE TITLE
Inconsistent column selection behavior?

### ISSUE THREAD

**Issue by peterbourgon** [cznic/ql#138]
```
ql 'CREATE TABLE foo (s string NOT NULL, t time NOT NULL);'
ql 'SELECT s FROM foo ORDER BY foo.t DESC LIMIT 1'   # no output, but OK
ql 'BEGIN TRANSACTION; INSERT INTO foo (s, t) VALUES ("bar", now()); COMMIT;'
ql 'SELECT s FROM foo LIMIT 1;'                      # "bar"
ql 'SELECT s FROM foo ORDER BY foo.t DESC LIMIT 1;'  # unknown field foo.t
```

I'm probably doing something wrong?

**Comment by cznic** [comment]
It's complicated, IINM ;-)

```bash
$ rm -f ql.db
$ ql 'CREATE TABLE foo (s string NOT NULL, t time NOT NULL);'
$ ql 'SELECT s FROM foo ORDER BY foo.t DESC LIMIT 1' # (1)
$ ql 'INSERT INTO foo (s, t) VALUES ("bar", now());'
$ ql 'SELECT s FROM foo LIMIT 1;'
"bar"
$ ql 'SELECT s, t FROM foo ORDER BY t DESC LIMIT 1' # (2)
"bar", 2016-10-13 18:13:15.457108189 +0200 CEST
$ 
```

The `ORDER BY` pipeline stage cannot check the validity of `foo.t` before getting the first result from the `SELECT` stage. The reason is that the particular combination of `select` and `from` can produce field names and field qualifiers not known at prepare ("compile") time. Select statements can be compiled before the underlying tables even exist.

In case `(1)` the pipeline produces no records, so the `order by` stage can never check the first record of the record set for matching/non matching field name, or qualifier.name, in this case `foo.t`, and cannot complain.

In case (2) it works, provided additionaly listing `t` as the output field (or using `*`), but the original `ORDER BY foo.t` will not, because the particular record set has no such named field.`

```bash
$ ql 'EXPLAIN SELECT s FROM foo ORDER BY foo.t DESC LIMIT 1'
┌Iterate all rows of table "foo"
└Output field names ["s" "t"]
┌Evaluate s as "s",
└Output field names ["s"]
┌Order descending by foo.t,
└Output field names ["s"]
┌Pass first 1 records
└Output field names [s]
$ 
```

**Comment by peterbourgon** [comment]
OK! Thanks for the fast reply and the workaround.
