### ISSUE TITLE
`NOT IN` don't work correctly

### ISSUE THREAD

**Issue by ta2gch** [cznic/ql#151]
I wanted to write an order where inserts occur only when there is no record. But the next command did not work well. Please tell me if there is another way. 

~~~sql
CREATE TABLE dual ( dummy BOOL);
CREATE TABLE member ( name STRING );
INSERT INTO dual VALUES ( false );
INSERT INTO member SELECT "john" FROM dual WHERE "john" NOT IN (SELECT name FROM member);
SELECT * FROM member;
~~~

~~~
john
~~~

SQLite3 print this, but ql print nothing.

**Comment by cznic** [comment]
I did not test SQLite3, but I believe it behaves differently. The problem is that ql seems to works as intended. Particularly [Predicates](https://godoc.org/github.com/cznic/ql#hdr-Predicates) say

> Predicates are special form expressions having a boolean result type.
>
> Expressions of the form
>
> `expr IN ( expr1, expr2, expr3, ... )		// case A`
>
> `expr NOT IN ( expr1, expr2, expr3, ... )	// case B`
>
> are equivalent, including NULL handling, to
>
> `expr == expr1 || expr == expr2 || expr == expr3 || ...	// case A`
>
> `expr != expr1 && expr != expr2 && expr != expr3 && ...	// case B`

Note the '*including NULL handling*'. Now consider:

```bash
$ ql 'create table member (name string); create table dual (dummy bool); insert into dual values (false)'
$ ql 'select "john" NOT IN ("mary") from dual'
true
$ ql 'select "john" NOT IN ("john") from dual'
false
$ ql 'SELECT name FROM member'
$ ql 'select "john" NOT IN (SELECT name FROM member) from dual'
<nil>
$ 
```

It is possible to change the handling of a empty list to work such that `in (NULL)` would produce `false` instead of `NULL`, but that may break existing ql code and so it's no more an option, unfortunately.

However, if changing the statement is an option, one can do:

```bash
$ ql 'create table member (name string); create table dual (dummy bool); insert into dual values (false)'
$ ql 'insert into member select "john" from dual where 0 in (select count() from member where name == "john")'
$ ql 'select * from member'
"john"
$ ql 'insert into member select "john" from dual where 0 in (select count() from member where name == "john")'
$ ql 'select * from member'
"john"
$ ql 'insert into member select "mary" from dual where 0 in (select count() from member where name == "mary")'
$ ql 'select * from member'
"mary"
"john"
$ ql 'insert into member select "john" from dual where 0 in (select count() from member where name == "john")'
$ ql 'select * from member'
"mary"
"john"
$
```

The execution cost of this variant is equal to that in the OP (and the `name` field should be indexed in any case). Which reminds me that simply creating an unique index on `name` would provide, IINM, the mostly same desired effect as any of the methods discussed in this issue and it might be the best choice.

WDYT?

**Comment by ta2gch** [comment]
Ok, That is, it is correct that the following code returns true.

~~~sql
SELECT ("john" NOT IN (SELECT name FROM member)) IS NULL FROM dual
~~~

Also thanks for presenting a solution.

I have a few of questions,

1. `<nil>` is equal to NULL?
2. in Golang,
	`SELECT 'john' NOT IN (SELECT name FROM member) FROM dual` also returns `<nil>`.
	Is it that we can not know that this code is returning NULL(or `<nil>`) till `rows.Scan`?
3. What does OP stands for?

Many thanks!

## Example

~~~go
package main

import (
	"fmt"
	"os"
	"github.com/cznic/ql"
	"database/sql"
)

func main(){
	ql.RegisterDriver()
	db, _ := sql.Open("ql","ql.db")

	// Setup
	tx, _ := db.
	Begin()
	tx.Exec("CREATE TABLE member (name STRING)")
	tx.Exec("CREATE TABLE dual (dummy bool)")
	tx.Exec("INSERT INTO dual VALUES(false)")
	tx.Commit()

	// Do
	var member bool
	stmt := `SELECT "john" NOT IN (SELECT * FROM member) FROM dual`
	rows, err := db.Query(stmt)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	for rows.Next() {
		if err := rows.Scan(&member); err != nil {
			fmt.Println(err)
			os.Exit(1)			
		}
	}
	
	fmt.Println(member)
}
~~~

**Comment by cznic** [comment]
>  `<nil>` is equal to NULL?

`<nil>` is produced by `fmt.Printf` for `nil` values and those represent the sql `NULL`, so yes.

> `SELECT 'john' NOT IN (SELECT name FROM member) FROM dual` also returns <nil>.
Is it that we can not know that this code is returning NULL(or `<nil>`) till `rows.Scan`?

I'm not sure how `rows.Scan` behaves and I did not yet tried your example code. I would only guess it just returns false for an empty recordset, ie. I think it in this case does not return an actual NULL row. (But something like `select null from dual` should return a NULL row, I believe).

> What does OP stands for?

It means the Original Post, it this case the [one that started this thread](https://github.com/cznic/ql/issues/151#issue-206962674).

**Comment by ta2gch** [comment]
Thanks for the answer.

> I'm not sure how rows.Scan behaves and I have not yet tried your example code. 

Okey, the result of example code is following.

~~~
sql: Scan error on column index 0: sql/driver: couldn't convert <nil> (<nil>) into type bool
exit status 1
~~~

So, `row.Scan` doesn't return false.
This may not be a problem of ql.

What do you think?

**Comment by cznic** [comment]
> This may not be a problem of ql.

That's possible but it seems to me it's is a problem in the client side code

```go
var member bool
...
if err := rows.Scan(&member); err != nil {
...
```

The above works if the scanned row is known to never have the NULL value (instead of a bool). In other cases the member should be, I believe, declared as

```go
var member sql.NullBool
```

At least I think so, as I don't think I've ever used any of the "nullable" types of the `sql` package. Can you please try with [`sql.NullBool`](https://golang.org/pkg/database/sql/#NullBool)? If that would not work either then there's definitely a bug in ql.

**Comment by ta2gch** [comment]
It's works. I didn't know `sql.NullBool`. 
It's big help. Thanks!!! (ql is very cool library :smile:)
