### ISSUE TITLE
quote of column name or table name

### ISSUE THREAD

**Issue by lunny** [cznic/ql#52]
When I want to use bool or other keywords as table's name or column's name, it will return syntax error, so I think we can use a qutoe charector to avoid this just like other DBMS. How can I do via ql? Or could you add some one?

**Comment by alexflint** [comment]
Without quoted identifiers it's quite difficult to make ORMs work with ql. The issue is that table names might be generated programmatically from e.g. the name of a struct, but then if the user passes a struct named `Table` then you end up with a syntax error. So the ORM needs a complete list of ql reserved words, which is tricky to maintain.
