### ISSUE TITLE
Column not null constraint support and default values

### ISSUE THREAD

**Issue by urandom** [cznic/ql#85]
Hi,

Is there currently any way to specify that a column cannot have null values, as well as having default values for columns? If not, I hope these features are considered for inclusion at some point.

**Comment by cznic** [comment]
No such way ATM. It's just a question of having enough time to implement it, as it involves new table metadata. The rest seems not too much complicated.

Support for default values is more or less like the above and so it probably would be the best to do both things at the same time.

**Comment by cznic** [comment]
@urandom please test and let me know of any problems you'll run into.

## Overview:

### Grammar change

```
ColumnDef = ColumnName Type
	[ "NOT" "NULL" | Expression ]
	[ "DEFAULT" Expression ] .
```

The optional constraint clause has two forms. The first one is found in many SQL dialects.

```sql
BEGIN TRANSACTION;
	CREATE TABLE department (
		DepartmentID   int,
		DepartmentName string NOT NULL,
	);
COMMIT;
```

This form prevents the data in column DepartmentName to be NULL.

The second form allows an arbitrary boolean expression to be used to validate the column. If the value of the expression if true then the validation succeeded. If the value of the expression if false or NULL then the validation fails. If the value of the expression is not of type bool an error occurs.

```sql
BEGIN TRANSACTION;
	CREATE TABLE department (
		DepartmentID   int,
		DepartmentName string DepartmentName IN ("HQ", "R/D", "Lab", "HR"),
	);
COMMIT;
```

```sql
BEGIN TRANSACTION;
	CREATE TABLE t (
		TimeStamp time TimeStamp < now() && since(TimeStamp) < duration("10s"),
		Event string Event != "" && Event like "[0-9]+:[ \t]+.*",
	);
COMMIT;
```

The optional DEFAULT clause is an expression which, if present, is substituted instead of a NULL value when the colum is assigned a value.

```sql
BEGIN TRANSACTION;
	CREATE TABLE department (
		DepartmentID   int,
		DepartmentName string DepartmentName IN ("HQ", "R/D", "Lab", "HR") DEFAULT "HQ",
	);
COMMIT;
```

Note that the constraint and/or default expressions may refer to other columns by name:

```sql
BEGIN TRANSACTION;
	CREATE TABLE t (
		a int,
		b int b > a && b < c DEFAULT (a+c)/2,
		c int,
);
COMMIT;
```

### Constraints and defaults

When a table row is inserted by the INSERT INTO statement or when a table row is updated by the UPDATE statement, the order of operations is as follows:

1. The new values of the affected columns are set and the values of all the row columns become the named values which can be referred to in default expressions evaluated in step 2.

2. If any row column value is NULL and the DEFAULT clause is present in the column's definition, the default expression is evaluated and its value is set as the respective column value.

3. The values, potentially updated, of row columns become the named values which can be referred to in constraint expressions evaluated during step 4.

4. All row columns which definition has the constraint clause present will have that constraint checked. If any constraint violation is detected, the overall operation fails and no changes to the table are made.

**Comment by urandom** [comment]
@cznic 
So far everything I tested works wonderfully, thanks.
